site_name: "Vaccine Informatics (VaxInfo) Consortium"
repo_url: https://vaccineinformatics.github.io/VaxInfo-Consortium/
edit_uri: '?query=root/VaxInfo-Consortium/docs/'
theme:
  name: readthedocs
nav:
  - Home: index.md
  - VaxInfo Introduction: vaxinfo_intro.md
  - Working Groups: working-groups.md
  - Participating organizations: organizations.md
  - Contact Information: contact.md
